version: '3.1'

services:

  gpt:
    build:
      context: .
      dockerfile: gpt.dockerfile
    volumes:
      - ./logs:/usr/src/app/logs
  
  dotesting:
    build:
      context: .
      dockerfile: dotesting.dockerfile
    volumes:
      - ./logs:/usr/src/app/logs

  moderadot:
    build:
      context: .
      dockerfile: moderadot.dockerfile
    volumes:
      - ./logs:/usr/src/app/logs
  
  infobot:
    build:
      context: .
      dockerfile: infobot.dockerfile
    volumes:
      - ./logs:/usr/src/app/logs

  server:
    build:
      context: .
      dockerfile: server.dockerfile
    volumes:
      - ./logs:/var/www/application/logs
    ports:
      - 5000:5000

  museum:
    build:
      context: .
      dockerfile: museum.dockerfile
    volumes:
      - ./logs:/usr/src/app/logs
      - ./museum.py:/usr/src/app/museum.py

  nginx:
    image: 'jc21/nginx-proxy-manager:latest'
    restart: unless-stopped
    ports:
      - 80:80
      - 81:81
      - 443:443
    volumes:
      - ../data:/data
      - ../letsencrypt:/etc/letsencrypt
  


  
